---
- name: install fail2ban
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - "{{ FAIL2BAN_PKGS_LIST }}"
  tags: pkg

- name: fail2ban config for ssh
  ansible.builtin.template:
    src: etc/fail2ban/jail.d/sshd.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    restart fail2ban
