- name: Ensure Log directory exists 
  ansible.builtin.file:
    path: /var/logs/nginx/whisper_backend/logs
    state: directory
    owner: www-data
    group: www-data
  

- name: Copy nginx backend config from template
  ansible.builtin.template:
    src: etc/nginx/sites-available/backend_nginx.conf.j2
    dest: /etc/nginx/sites-available/whisper_backend.config
  notify: restart nginx

- name: link to sites-enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/whisper_backend.config
    dest: /etc/nginx/sites-enabled/whisper_backend.config
    state: link
    force: yes 

