---
- name: Ensure web root exists
  ansible.builtin.file:
    path: "{{ WEB_ROOT }}"    
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

# Copy config from template
- name: Copy nginx frontend config from template
  ansible.builtin.template:
    src: etc/nginx/sites-available/frontend.conf.j2
    dest: /etc/nginx/sites-available/{{ DOMAIN }}
  notify: restart nginx

- name: link to sites-enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ DOMAIN }}
    dest: /etc/nginx/sites-enabled/{{ DOMAIN }}
    state: link
    force: yes 


